/**
 * \file cpaceoquake.h
 *
 * \brief Hybrid PAKE of combined CPace and OQUAKE.
 */
/*
 *  Copyright Nick Leist
 */
#ifndef CPACEOQUAKE_H
#define CPACEOQUAKE_H

#define CPACEOQUAKE_DST "CPACEOQUAKE-v1.0.0"
#define CPACEOQUAKE_DST_LEN 19
#define CPACEOQUAKE_NKEY 32

#include <stdint.h>

#include "crypto_cpace.h"
#include "oquake.h"

/*
 * J-PAKE is a password-authenticated key exchange that allows deriving a
 * strong shared secret from a (potentially low entropy) pre-shared
 * passphrase, with forward secrecy and mutual authentication.
 * https://en.wikipedia.org/wiki/Password_Authenticated_Key_Exchange_by_Juggling
 *
 * This file implements the Elliptic Curve variant of J-PAKE,
 * as defined in Chapter 7.4 of the Thread v1.0 Specification,
 * available to members of the Thread Group http://threadgroup.org/
 *
 * As the J-PAKE algorithm is inherently symmetric, so is our API.
 * Each party needs to send its first round message, in any order, to the
 * other party, then each sends its second round message, in any order.
 * The payloads are serialized in a way suitable for use in TLS, but could
 * also be use outside TLS.
 */

/**
 * CpaceOQUAKE context structure to be stored by the initiator
 */
typedef struct cpaceoquake_initiator_ctx {
    crypto_cpace_state *cp_ctx;
    uint8_t *s1;
} cpaceoquake_initiator_ctx;

/**
 * CpaceOQUAKE context structure to be stored by the responder
 */
typedef struct cpaceoquake_responder_ctx {
    uint8_t *fullsid;
    size_t fullsid_len;
    uint8_t *prs;
    size_t prs_len;
    uint8_t *msg1;
    size_t msg1_len;
    uint8_t *msg2;
    size_t msg2_len;
    uint8_t *msg3;
    size_t msg3_len;
    uint8_t *key1B;
    oquake_initiator_ctx *oq_ctx;
} cpaceoquake_responder_ctx;

/**
 * \brief           Encodes a byte string with a two-byte, big-endian length prefix.
 *
 * \param msg       Message to be encoded
 * \param msg_len   Length of msg in bytes
 * \param out       Output buffer for encoded msg
 *
 * \return          Pointer to the encoded message
 *
 */
int lv_encode(const uint8_t *msg, size_t msg_len, uint8_t **out);

/**
 * \brief           Decodes a byte string assumed to have a two-byte, big-endian length prefix.
 *
 * \param msg       Message to be decoded (is performed in-place)
 *
 * \return          Length of the decoded message
 *
 */
size_t lv_decode(uint8_t *msg);

/**
 * \brief           Creates init message of CPaceOQUAKE flow 
 *
 * \param prs       Password-related string / Password
 * \param prs_len   Length of the password-related string
 * \param sid       Session ID
 * \param sid_len   Length of session ID
 * \param u         Client identifier
 * \param s         Server identifier
 *
 * \param[out] ctx      Will contain the opaque context to be stored by the initiator
 * \param[out] init_msg Pointer to the message bytestring output of the function
 *
 * \return          \c 0 if successful.
 * \return          A negative error code on failure.
 */
int cpaceoquake_init(const unsigned char *prs, size_t prs_len,
                    const uint8_t *sid, size_t sid_len,
                    const uint8_t u[16], const uint8_t s[16],
                    cpaceoquake_initiator_ctx *ctx, uint8_t **init_msg);

/**
 * \brief           Processes init message and creates response message of CPaceOQUAKE flow. 
 *                  Computes also the shared secret.
 *
 * \param prs       Password-related string
 * \param prs_len   Length of the password-related string
 * \param init_msg  Init message received from initiator
 * \param sid       Session ID
 * \param sid_len   Length of session ID
 * \param u         Client identifier
 * \param s         Server identifier
 *
 * \param[out] ctx      Will contain the opaque context to be stored by the responder
 * \param[out] resp_msg Pointer to the message bytestring output of the function
 *
 * \return          \c 0 if successful.
 * \return          A negative error code on failure.
 */
int cpaceoquake_respond(unsigned char *prs, size_t prs_len,
                    uint8_t *init_msg,
                    const uint8_t *sid, size_t sid_len,
                    uint8_t u[16], uint8_t s[16],
                    cpaceoquake_responder_ctx *ctx, uint8_t **resp_msg);

/**
 * \brief           Processes response message and computes the shared secret and the final message
 *
 * \param prs       Password-related string
 * \param prs_len   Length of the password-related string
 * \param ctx       CPaceOQUAKE initiator context generated by cpaceoquake_init()
 * \param resp_msg  Response message received from responder
 * \param sid       Session ID
 * \param sid_len   Length of session ID
 * \param u         Client identifier
 * \param s         Server identifier
 *
 * \param[out] key          Shared Secret of N bytes
 * \param[out] key_len      Length of key in bytes
 * \param[out] fin_msg      Final message to send to responder
 * \param[out] fin_msg_len  Length of fin_msg in bytes
 *
 * \return          \c 0 if successful.
 * \return          A negative error code on failure.
 */
int cpaceoquake_initiator_finish(const unsigned char *prs, size_t prs_len,
    const cpaceoquake_initiator_ctx *ctx, uint8_t *resp_msg,
    const uint8_t *sid, size_t sid_len,
    uint8_t u[16], uint8_t s[16],
    uint8_t **key, size_t *key_len,
    uint8_t **fin_msg, size_t *fin_msg_len);

/**
 * \brief           Processes final message and computes the shared secret
 *
 * \param ctx           CPaceOQUAKE responder context generated by cpaceoquake_respond()
 * \param fin_msg       Final message received from initiator
 * \param fin_msg_len   Length of fin_msg in bytes
 *
 * \param[out] key      Shared secret, byte string of 32 bytes
 * \param[out] key_len  Length of key in bytes
 *
 * \return          \c 0 if successful.
 * \return          A negative error code on failure.
 */
int cpaceoquake_responder_finish(cpaceoquake_responder_ctx *ctx, uint8_t *fin_msg, 
    size_t fin_msg_len, uint8_t **key, size_t *key_len);


#endif /* CPACEOQUAKE_H */
